# -*- coding: utf-8 -*-
"""지능형 기차2_24-02-24_이현지.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WOjFmV9LP81-yQ_lA0WN89Y4NkTCQIws
"""

leftPeople = [] # 남은 승객 수를 담는 리스트
out, get = map(int, input().split()) # 내린사람 수, 탄 사람 수 입력값
leftPeople.append(get - out) # 1번역

for i in range(9): # 2번역부터 10번역까지
    out, get = map(int, input().split())
    leftPeople.append((get-out) + leftPeople[i]) #내린사람 수와 탄사람 수를 뺀 값에서 전 역에 남아있는 사람들 더한 수를 leftPeople 리스트에 추가해야함
print(max(leftPeople)) # 그 중 가장 큰 수를 출력하면 됨

