# -*- coding: utf-8 -*-
"""Bronze3_이윤재_240219.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gdm-GigM_XgChbPlOgxfGUYkoLqgvbLw
"""

x, y, w, h = map(int, input().split())
print(min(x, y, h-y, w-x))