# -*- coding: utf-8 -*-
"""I_Work_All_Day_24-02-22_이현지.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1648fTwjZ2ynNG8yJdE6qKtfi7AkDiJKp
"""

num = int(input()) #설정 수
machin = input().split() #자를 설정값들 -> 리스트로 담음
treeLen = int(input()) #나무 길이

result = {}
for i in range(num):
    result[int(treeLen) % int(machin[i])] = machin[i] # 딕셔너리에 키 벨류를 추가하여

print(result[min(result.keys())]) # 최소값을 갖은 키값을 출력!!