# -*- coding: utf-8 -*-
"""사탕선생고창영_24-02-27_이현지.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XwRM9WfrVwa2wuuCx0mzFX2djqf04Ktm
"""

T = int(input()) # 테스트 케이스 개수

candylist = [] # 가져온 사탕 저장

for i in range(T):
    input() #-> 이건 억까야;;
    n = int(input()) #학생 수
    candylist.append([int(input()) for j in range(n)]) #[[5, 2, 7, 3, 8], [7, 11, 2, 7, 3, 4]]

    if sum(candylist[i])%len(candylist[i]) == 0: # i번째 리스트의 합과 i번째 리스트 길이 나머지 계산
        print('YES')
    else:
        print('NO')