# -*- coding: utf-8 -*-
"""별 찍기_24-02-23_이현지.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oSGyX9nohFc4P-5fwtR9MwyRNtMUBXDS
"""

num = int(input()) # 입력할 정수값
space = ' '
star = '*'
for i in range(num): #[0, 1, 2, 3, 4] -> 공백 space와 별 star를 출력을 반복문을 통해 출력해볼거임!!
    print((space*i) + (star*(2*num-2*i-1))) # 여기서 내가 실수한게,, print((space*i) + (star*(2*num-2*i-1)) + (space*i)) 뒤에도 마찬가지로 공백을 출력해야된다고 생각함!! 다시 생각해보니 굳이 필요없는 코드였음

