# -*- coding: utf-8 -*-
"""얼룩말을 찾아라!_24-02-05_이현지.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sq_L5axZ0ZIb9OzSKjBrhMZyPHMP0D1L
"""

N, L = map(int, input().split()) # 얼룩말 개체수와 몸통 길이

result = [] # 얼룩말 줄무늬 개수 담을 빈 리스트
for i in range(N):
    lineInput = input() # 얼룩말 털상태 값
    if len(lineInput) != L: # 얼룩말 몸통길이 L과 입력한 털상태 길이가 같지 않으면 실행을 멈추게 함
        break
    line = lineInput.split('0') # 0값으로 끊은 얼룩말 줄무늬
    blackLines = [j for j in line if j != ''] # 여기서 좀 헤맸다!!! 조건문에 ''은 제외시기고 줄무늬만 리스트 안에 들어가게 할당 -> 110010101 를 이렇게 ['11', '1', '1', '1']
    # print(blackLines)
    result.append(len(blackLines)) # 길이만 저장

    maxLines = max(result) # 가장 많은 줄무늬 수
    hours = result.count(maxLines) # 가장 많은 줄무늬 수를 갖고있는 말의 수

print(maxLines, hours)

